### PR TITLE
Fix the default choice in the destroy model's warning message

### PR DESCRIPTION
**Pull request by Jumanjii**

### CODE REVIEW

**Comment by markbates** [comment]
This appears to be failing on windows, can you please investigate? Thanks.

**Comment by lukasschlueter** [comment]
Windows tests are actually failing since 316bdb5cb68ebc4f29d675941a3bf58fafa096e0, I'm not sure why though...

**Comment by stanislas-m** [comment]
@lukasschlueter There's an unrelated bug in SQLite URL parsing on Windows, this should fix it: https://github.com/gobuffalo/pop/pull/339

**Review by stanislas-m — APPROVED** [review]

**Comment by stanislas-m** [comment]
Thanks!

**Pull request merged**
